### ISSUE TITLE
感谢！期待web版！

### ISSUE THREAD

**Issue by qiang-007** [AnsGoo/PyPicGo#3]
非常好用的工具，期待整个成web版

**Comment by AnsGoo** [comment]
这个本身是一个命令行工具，定位是图床的Client端的框架，你可以用它集成你想要的任何图床工具，所以Web版的意义在哪里？你希望它有一个Web版，那么你的需求是什么？
看过PicGo的桌面端应用，它除过实现我的功能外，它类似在桌面上集成了一个WebServer，这样可以实现了对上传历史的管理和其他的功能，例如剪贴板监听，这些额外功能都要求它必须常驻后台，这样他就必须长期占用端口和内存等计算机资源，对一个图床工具而言，我觉得没必要。
PyPicGo用完就释放完所有资源，不占用端口、不消耗资源，也不会监听你的任何信息！
欢迎开发自己的图床插件，或者有好的想法可以反馈，我们一起来完善PyPicGo的生态！

**Comment by qiang-007** [comment]
> 

因为我有多台不同系统的设备，想着如果能有一个web版，把picgo安装在远程服务器，其他设备只需通过一个简单的脚本连接服务器上传图片到图库就行了。而且，不仅适用多台设备，还适用不同程序。 😊😊

**Comment by AnsGoo** [comment]
你可以自己写个服务端，并暴露接口，调用PyPicGo就可以了，这个应该很容易实现，这个需求不能接受，PyPicGo一般不会引入大的依赖
